### ISSUE TITLE
wtコマンドでNullPointerExceptionが発生する

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#204]
develop_todoで貼ったエラーです。

`at com.jaoafa.mymaid4.command.Cmd_Wt.worldTeleport(Cmd_Wt.java:83) ~[?:?]` (`null`)
```[21:21:05] [Server thread/ERROR]: [MyMaid4] Exception executing command handler
java.lang.NullPointerException: null
at com.jaoafa.mymaid4.lib.MyMaidLibrary.getGroundPos(MyMaidLibrary.java:369) ~[?:?]
at com.jaoafa.mymaid4.command.Cmd_Wt.worldTeleport(Cmd_Wt.java:83) ~[?:?]
at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121) ~[?:?]
at cloud.commandframework.CommandManager.executeCommand(CommandManager.java:176) ~[?:?]
at cloud.commandframework.bukkit.BukkitCommand.execute(BukkitCommand.java:91) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-574]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-574]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168) ~[patched_1.16.5.jar:git-Paper-574]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983) ~[patched_1.16.5.jar:git-Paper-574]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936) ~[patched_1.16.5.jar:git-Paper-574]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-574]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-574]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-574]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-574]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-574]
at net.mine...

**Comment by book000** [comment]
https://github.com/jaoafa/MyMaid4/blob/e7e7f553f4005f1fe93133d1f1133f3d10cb2b22/src/main/java/com/jaoafa/mymaid4/command/Cmd_Wt.java#L80
この後にreturnが足りない？
