### ISSUE TITLE
[Cmd_G] java.lang.IllegalArgumentException: Mode cannot be null

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#25]
```
[13:46:17 ERROR]: [MyMaid4] Exception executing command handler
java.lang.IllegalArgumentException: Mode cannot be null
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:1186) ~[patched_1.16.5.jar:git-Paper-547]
        at com.jaoafa.mymaid4.command.Cmd_G.changeGamemode(Cmd_G.java:138) ~[?:?]
        at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121) ~[?:?]
        at cloud.commandframework.CommandManager.executeCommand(CommandManager.java:176) ~[?:?]
        at cloud.commandframework.bukkit.BukkitCommand.execute(BukkitCommand.java:91) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-547]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2023) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1838) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1791) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1140) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1094) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1008) ~[patched_1.16.5.jar:git-Paper-547]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-547]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
```

**Comment by yuuahp** [comment]
defaultValueをnullじゃなくてcreativeにしてみたんですがどうですか

**Comment by yuuahp** [comment]
(どうやったらバグ再現できますか)

**Comment by book000** [comment]
コマンド `/g test` 実行

**Comment by yuuahp** [comment]
![image](https://user-images.githubusercontent.com/53546237/111859618-87fb9680-8985-11eb-841f-2ccddcad1957.png)
ちゃんと見つかりませんって出ます

**Comment by yuuahp** [comment]
/g survival darekasan
だとエラー出るんですがそれですか

**Comment by yuuahp** [comment]
あ～～～～～

**Comment by yuuahp** [comment]
でます

**Comment by yuuahp** [comment]
修正しました

**Comment by book000** [comment]
問題なさげなのでプルリク送ってくださーい。その後gのサジェスト機能追加します。

**Comment by yuuahp** [comment]
送ります
