### ISSUE TITLE
コマンドブロックからwtコマンドが実行された際にうまく動作しない不具合

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid4#268]
[Cmd_Wt:100] java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R3.command.CraftBlockCommandSender cannot be cast to org.bukkit.entity.Player

### Stacktrace

```
[MyMaid4] Exception executing command handler
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R3.command.CraftBlockCommandSender cannot be cast to org.bukkit.entity.Player
	at com.jaoafa.mymaid4.command.Cmd_Wt.worldTeleportPlayer(Cmd_Wt.java:100) ~[?:?]
	at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121) ~[?:?]
	at cloud.commandframework.CommandManager.executeCommand(CommandManager.java:176) ~[?:?]
	at cloud.commandframework.bukkit.BukkitCommand.execute(BukkitCommand.java:91) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.craftbukkit.v1_16_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:53) ~[patched_1.16.5.jar:git-Paper-574]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[patched_1.16.5.jar:git-Paper-574]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:267) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:248) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.CommandDispatcher.dispatchServerCommand(CommandDispatcher.java:244) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:134) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.BlockCommand.a(BlockCommand.java:119) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.BlockCommand.tickAlways(BlockCommand.java:106) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:617) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.WorldServer.b(WorldServer.java:921) ~[patched_1.16.5.jar:git-Paper-574]
	at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:306) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.TickListServer.b(TickListServer.java:59) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:579) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1476) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-574]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

### LINK

https://github.com/jaoafa/MyMaid4/blob/master/src/main/java/com/jaoafa/mymaid4/command/Cmd_Wt.java#L100

**Comment by book000** [comment]
次の方法で解決できます。開発を始める前に [CONTRIBUTING](https://github.com/jaoafa/MyMaid4/blob/master/CONTRIBUTING.md) を確認してください。

`worldTeleportPlayer` メソッド内において実行者がプレイヤーでない可能性があるので `CommandSender` のまま処理するように変更する
