### ISSUE TITLE
[Event_Antijaoium:164] java.lang.NoSuchMethodError: okhttp3.internal.Util.immutableList(Ljava/util/List;)Ljava/util/List;

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid4#293]
### Stacktrace
[Event_Antijaoium:164] java.lang.NoSuchMethodError: okhttp3.internal.Util.immutableList(Ljava/util/List;)Ljava/util/List;

```
Could not pass event PlayerItemHeldEvent to MyMaid4 v2021.04.29_22.01_e25c261
java.lang.NoSuchMethodError: okhttp3.internal.Util.immutableList(Ljava/util/List;)Ljava/util/List;
	at okhttp3.MultipartBody.<init>(MultipartBody.java:78) ~[?:?]
	at okhttp3.MultipartBody$Builder.build(MultipartBody.java:342) ~[?:?]
	at net.dv8tion.jda.internal.requests.restaction.MessageActionImpl.asMultipart(MessageActionImpl.java:497) ~[?:?]
	at net.dv8tion.jda.internal.requests.restaction.MessageActionImpl.finalizeData(MessageActionImpl.java:611) ~[?:?]
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:190) ~[?:?]
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:563) ~[?:?]
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:529) ~[?:?]
	at com.jaoafa.mymaid4.event.Event_Antijaoium.saveItem(Event_Antijaoium.java:164) ~[?:?]
	at com.jaoafa.mymaid4.event.Event_Antijaoium.check(Event_Antijaoium.java:303) ~[?:?]
	at com.jaoafa.mymaid4.event.Event_Antijaoium.onPlayerItemHeldEvent(Event_Antijaoium.java:251) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor495.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-574]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1905) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.PacketPlayInHeldItemSlot.a(SourceFile:30) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.PacketPlayInHeldItemSlot.a(SourceFile:8) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1381) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-574]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

### LINK

https://github.com/jaoafa/MyMaid4/blob/master/src/main/java/com/jaoafa/mymaid4/event/Event_Antijaoium.java#L164

**Comment by book000** [comment]
#290
