### ISSUE TITLE
[Event_DisableConcreteTransition:50] java.lang.IllegalArgumentException: Particle FALLING_DUST requires data, null provided

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid4#388]
### Stacktrace
[Event_DisableConcreteTransition:50] java.lang.IllegalArgumentException: Particle FALLING_DUST requires data, null provided (23:03:53)

```
Could not pass event BlockFormEvent to MyMaid4 v2021.05.08_21.38_2f33981
java.lang.IllegalArgumentException: Particle FALLING_DUST requires data, null provided
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.craftbukkit.v1_16_R3.CraftParticle.toNMS(CraftParticle.java:146) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2524) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2514) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2503) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2483) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2473) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnParticle(CraftWorld.java:2468) ~[patched_1.16.5.jar:git-Paper-574]
	at com.jaoafa.mymaid4.event.Event_DisableConcreteTransition.onBlockFormEvent(Event_DisableConcreteTransition.java:50) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor461.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-574]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1698) ~[patched_1.16.5.jar:git-Paper-574]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1690) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.BlockConcretePowder.a(BlockConcretePowder.java:33) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.EntityFallingBlock.tick(EntityFallingBlock.java:195) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:959) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.World.a(World.java:946) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:644) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1476) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-574]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-574]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

### LINK

https://github.com/jaoafa/MyMaid4/blob/master/src/main/java/com/jaoafa/mymaid4/event/Event_DisableConcreteTransition.java#L50

**Comment by book000** [comment]
#265 と同じ。FALLING_DUSTがdataを必須としてるんだけど、指定されてないよということ

**Comment by book000** [comment]
他にも

```

java.lang.IllegalArgumentException: Particle BLOCK_CRACK requires data, null provided
java.lang.IllegalArgumentException: Particle FALLING_DUST requires data, null provided
java.lang.IllegalArgumentException: Particle ITEM_CRACK requires data, null provided
java.lang.IllegalArgumentException: Particle LEGACY_BLOCK_CRACK requires data, null provided
java.lang.IllegalArgumentException: Particle LEGACY_BLOCK_DUST requires data, null provided
java.lang.IllegalArgumentException: Particle LEGACY_FALLING_DUST requires data, null provided
java.lang.IllegalArgumentException: Particle REDSTONE requires data, null provided
```

Legacy系は除外しても良いかも？

**Comment by book000** [comment]
## この機能の説明

コンクリートパウダーに水が触れた際、コンクリートになってしまう仕様を無効化してついでに無効化したことを示すためランダムにパーティクルを出す処理を実装しています。

## このバグの原因

Minecraftのパーティクルには、一部そのパーティクルで使用するブロックの情報などを要求するパーティクルがあります。
そのようなパーティクルがランダムで選ばれた場合、指定されていないために上記のようなエラーが発生します。

## 対処方法

そのような追加の情報を必要とするパーティクルをランダムに選ぶ一覧から削除することで、選ばれないようにします。

まずは追加情報を必要とするパーティクルが他にないかを調べます。
その後、それらのパーティクルをparticle.removeでランダム取得元一覧から削除します。また、LEGACY_から始まるパーティクルは古いバージョンとの互換性のために残されているので、それらも除外します。
