### ISSUE TITLE
weatherコマンドにおいてWeatherTypeの値にない値を引数に渡すと動作しない

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid4#494]
### Stacktrace
[Cmd_Weather:59] 	at com.jaoafa.mymaid4.command.Cmd_Weather.weatherSetByName(Cmd_Weather.java:59) (18:01:08)

```
	at com.jaoafa.mymaid4.command.Cmd_Weather.weatherSetByName(Cmd_Weather.java:59)
```

### LINK

https://github.com/jaoafa/MyMaid4/blob/master/src/main/java/com/jaoafa/mymaid4/command/Cmd_Weather.java#L59

**Comment by book000** [comment]
`java.lang.IllegalArgumentException` (`[18:01:08] [Server thread/WARN]: 	at java.base/java.lang.Enum.valueOf(Enum.java:240)`)

```
[18:01:08] [Server thread/WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.WeatherType.RUN
[18:01:08] [Server thread/WARN]: 	at java.base/java.lang.Enum.valueOf(Enum.java:240)
[18:01:08] [Server thread/WARN]: 	at org.bukkit.WeatherType.valueOf(WeatherType.java:6)
[18:01:08] [Server thread/WARN]: 	at com.jaoafa.mymaid4.command.Cmd_Weather.weatherSetByName(Cmd_Weather.java:59)
[18:01:08] [Server thread/WARN]: 	at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121)
[18:01:08] [Server thread/WARN]: 	at cloud.commandframework.CommandManager.executeCommand(CommandManager.java:176)
[18:01:08] [Server thread/WARN]: 	at cloud.commandframework.bukkit.BukkitCommand.execute(BukkitCommand.java:91)
[18:01:08] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[18:01:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[18:01:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[18:01:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[18:01:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[18:01:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[18:01:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[18:01:08] [Server thread/WARN]: 	at net.mine...
