### ISSUE TITLE
[Event_TpAlias:44] org.json.JSONException: JSONObject["data"] is not a string.

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid4#678]
### Stacktrace
[Event_TpAlias:44] org.json.JSONException: JSONObject["data"] is not a string. (16:17:32)

```
Could not pass event PlayerCommandPreprocessEvent to MyMaid4 v4.10.0
org.json.JSONException: JSONObject["data"] is not a string.
	at org.json.JSONObject.wrongValueFormatException(JSONObject.java:2694) ~[MyMaid4-v4.10.0.jar:?]
	at org.json.JSONObject.getString(JSONObject.java:871) ~[MyMaid4-v4.10.0.jar:?]
	at com.jaoafa.mymaid4.lib.TeleportAlias.toMap(TeleportAlias.java:81) ~[MyMaid4-v4.10.0.jar:?]
	at com.jaoafa.mymaid4.lib.TeleportAlias.load(TeleportAlias.java:72) ~[MyMaid4-v4.10.0.jar:?]
	at com.jaoafa.mymaid4.lib.TeleportAlias.getReplaceAlias(TeleportAlias.java:44) ~[MyMaid4-v4.10.0.jar:?]
	at com.jaoafa.mymaid4.event.Event_TpAlias.onTeleportCommand(Event_TpAlias.java:44) ~[MyMaid4-v4.10.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor454.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-160]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2279) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2098) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2079) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-160]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-160]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### LINK

https://github.com/jaoafa/MyMaid4/blob/master/src/main/java/com/jaoafa/mymaid4/event/Event_TpAlias.java#L44

**Comment by book000** [comment]
fixed: 古い設定ファイル残したままだった
