### ISSUE TITLE
cloudフレームワークのエラー？

### ISSUE THREAD

**Issue by book000** [jaoafa/MyMaid4#776]
```diff
- [2022/04/06 17:14:12 ERROR Minecraft] Could not pass event AsyncTabCompleteEvent to MyMaid4 v4.19.2
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
	at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2349)
	at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:1288)
	at net.minecraft.commands.arguments.selector.EntitySelector.addEntities(EntitySelector.java:165)
	at net.minecraft.commands.arguments.selector.EntitySelector.findEntities(EntitySelector.java:152)
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.selectEntities(CraftServer.java:2627)
	at org.bukkit.Bukkit.selectEntities(Bukkit.java:2166)
	at MyMaid4-v4.19.2.jar//cloud.commandframework.bukkit.parsers.selector.SingleEntitySelectorArgument$SingleEntitySelectorParser.parse(SingleEntitySelectorArgument.java:160)
	at MyMaid4-v4.19.2.jar//cloud.commandframework.CommandTree.suggestionsForDynamicArgument(CommandTree.java:646)
	at MyMaid4-v4.19.2.jar//cloud.commandframework.CommandTree.getSuggestions(CommandTree.java:555)
	at MyMaid4-v4.19.2.jar//cloud.commandframework.CommandTree.getSuggestions(CommandTree.java:517)
	at MyMaid4-v4.19.2.jar//cloud.commandframework.CommandTree.getSuggestions(CommandTree.java:517)
	at MyMaid4-v4.19.2.jar//cloud.commandframework.CommandTree.getSuggestions(CommandTree.java:478)
	at MyMaid4-v4.19.2.jar//cloud.commandframework.arguments.DelegatingCommandSuggestionEngine.getSuggestions(DelegatingCommandSuggestionEngine.java:75)
	at MyMaid4-v4.19.2.jar//cloud.commandframework.CommandManager.suggest(CommandManager.java:207)
	at MyMaid4-v4.19.2.jar//cloud.commandframework.paper.AsyncCommandSuggestionsListener.onTabCompletion(AsyncCommandSuggestionsListener.java:67)
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	at or```

**Comment by book000** [comment]
普通にこれ、なんで起きるのかわからん

**Comment by book000** [comment]
```diff
  [2022/04/06 17:14:13 INFO  Server/PlayerConnection] kohonayoshi issued server command: /rider ride @e[type=ender_dragon,limit=1] @e[type=wither,limit=1]```

？

**Comment by book000** [comment]
https://github.com/Incendo/cloud/blob/0623bcb050f5c3928b3201b62b9ccab3876e964a/cloud-minecraft/cloud-bukkit/src/main/java/cloud/commandframework/bukkit/parsers/selector/SingleEntitySelectorArgument.java#L160

これだな〜。小さいプラグイン作って検証するしかないな
