### ISSUE TITLE
[Event_PlayerCheckPreLogin:106] java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "countryName" is null

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid4#823]
### Stacktrace
[Event_PlayerCheckPreLogin:106] java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "countryName" is null (20:38:28)

```
Could not pass event AsyncPlayerPreLoginEvent to MyMaid4 v4.25.2
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "countryName" is null
	at com.jaoafa.mymaid4.event.Event_PlayerCheckPreLogin.OnEvent_PlayerCheckPreLogin(Event_PlayerCheckPreLogin.java:106) ~[MyMaid4-v4.25.2.jar:?]
	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-240]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:399) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl$2.run(ServerLoginPacketListenerImpl.java:339) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### LINK

https://github.com/jaoafa/MyMaid4/blob/master/src/main/java/com/jaoafa/mymaid4/event/Event_PlayerCheckPreLogin.java#L106

**Comment by book000** [comment]
国情報取得不能の場合、とりあえず不許可にする？
